services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    ports:
      - "54320:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  data: